name: Deploy app-demo to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      id: init
      run: terraform init

    - name: Terraform Validate
      env:
        ACCESS_KEY=${{ secrets.ACCESS_KEY }}
        SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      env:
        ACCESS_KEY=${{ secrets.ACCESS_KEY }}
        SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

